### ISSUE TITLE
turn off reports in inform mode?

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-lynis#7]
I like to run cf-agent -KI manually a lot. This policy clutters up my output with reports about issues found.

https://github.com/nickanderson/cfengine-lynis/blob/master/policy/main.cf#L274

Would you consider change the level to verbose possibly? Or maybe a specific class like -Dlynis_info?

**Comment by nickanderson** [comment]
Actually, I think that output is better suited for *verbose* level logging.

Inform level logging is supposed to contain information about changes cfengine made. I don't think the result of parsing a file really fits that category well. I just am bad about putting stuff in inform level logging because it's not so noisy.
